os: linux
arch: ppc64le
language: python
python:
    - "3.7"
notifications:
    irc:
        - "chat.freenode.net#unary"
    email:
        - "admin@unary.ca"
env:
    - PYTHONPATH=./
install:
    - pip install tox
    - pip install coveralls
script:
    - sed -i '2s/py26,py27,py34/py27/' tox.ini
    - python setup.py test
after_success:
    - coveralls
